
service: scraper-pokemon-puppeteer

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x


functions:
  hello:
    handler: handler.hello
    layers: 
      - arn:aws:lambda:us-east-1:366285556822:layer:chrome:1
    timeout: 100
    events:
      - http:
          method: GET
          path: "/"
          integration: lambda
          request:    
            parameters:
              querystrings: #configura o prox do api gatway para receber o parametro pokemon 
                pokemon: true 

plugins:
  - serverless-offline